name: clair-scan
description: 'run clair scan against docker image'

runs:
  using: composite
  steps:
    - name: login to docker
      uses: bruce1237/github_workflow_center/.github/actions/docker-login@main
      with:
       github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: dash branch name
      uses: bruce1237/github-workflow-center/.github/actions/dash-branch-name@main

    - name: check image before pull
      shell: bash
      run: docker images

    - name: pull image
      shell: bash
      run: docker pull ghcr.io/${{ github.repository }}:${{ env.branch_name }}

    - name: check image after pull
      shell: bash
      run: docker images

    - name: checkout chair-scan
      uses: actions/checkout@v3
      with:
       repository: arminc/clair-scanner
    
    - name: check dir
      shell: bash
      run: ls -lah

    - name: copy example-run.sh
      shell: bash
      run: |
        cp ./example-run.sh scan.sh
        chmod +x scan.sh
        scan.sh '${{ github.repository }}:${{ env.branch_name }}'