name: test-input-output
description: 'test action input output'

inputs:
  user_name:
    description: "the name of user"

outputs:
  user_age: ${{ steps.test-in-out-put.outputs.user_age }}
    

runs:
  using: composite
  steps:
    - shell: bash
      id: test-in-out-put
      run: |
        userName=${{ inputs.user_name }}
        echo 'user name is ' ${userName}
        age=99
        echo 'user_age=${age}' >> $GITHUB_OUTPUT
        