name: change branch name 
description: 'replace slash / to dash - in branch name, then assign to env.branch_name'
inputs:
  branch-name:
    description: 'the name of the branch'

runs:
  using: composite
  steps:
    - shell: bash
      name: replace / to -
      run: |
        removed_branch=${{ inputs.branch-name }}

        if [ -z ${removed_branch} ]
        then
          removed_branch=${GITHUB_REF_NAME}
          # echo "branch_name=${GITHUB_REF_NAME////-}" >> $GITHUB_ENV
        # else
        #   echo "branch-name is set"
        #   echo "branch_name=${removed_branch////-}" >> $GITHUB_ENV
        fi
          echo "branch_name=${removed_branch////-}" >> $GITHUB_ENV
    - shell: bash
      name: replace with sed
      run: |
        removed_branch='brach-a/b.c_e/f.g'


        
        echo "converted_branch=$(echo $removed_branch | sed -e 's/[/_]/-/g')" >> $GITHUB_ENV

        echo 'CONVERT COMPLETEED'
        echo ${converted_branch}

