name: change branch name 
description: 'replace slash / to dash - in branch name, then assign to env.branch_name'
  
runs:
  using: composite
  steps:
    - shell: bash
      name: replace / to -
      run: |
        removed_branch=${{ github.event.ref }}
        echo "branch_name=${removed_branch////-}" >> $GITHUB_ENV