name: docker-login
description: 'login to docker'
inputs:
  github_token:
    description: 'used to login to docker'

runs:
  using: composite
  steps:
    - name: login to github container registry
      uses: docker/login-action@v2
      with: 
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}