name: using-input-output
on:
  workflow_call:
   
jobs:
  using-input:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.second-stp.outputs.sec-out }}

    steps:
      - name: calling input action
        id: first-stp
        uses: bruce1237/github-workflow-center/.github/actions/input-output@main
        with:
          user_name: 'this-is-user-name-value'

      - name: check output same runner 
        run: echo age is ${{ steps.first-stp.outputs.random-number }}
      - name: assign the step output to job output
        id: second-stp
        run: |
          echo "sec-out=${{ steps.first-stp.outputs.random-number }}" >> $GITHUB_OUTPUT



  checking-output:
    runs-on: ubuntu-latest
    needs: using-input

    steps:
      - name: check out put
        run: echo age is ${{ needs.using-input.outputs.output1 }}
    
