name: clair-scan
on:
  workflow_call:
    inputs:
      github_token:
        type: string
        required: true
      image_name:
        type: string
        required: true
      image_tag:
        type: string
        required: true

    
jobs:
  clair-scan:
    runs-on: ubuntu-latest
   
    steps:
      - name: use clair-scan
        uses: bruce1237/github-workflow-center/.github/actions/clair-scan@main
        with:
          github_token: ${{ inputs.github_token }}
          image_name: ${{ inputs.image_name }}
          image_tag: ${{ inputs.image_tag }}
