name: clair-scan
on:
  workflow_call:
    inputs:
      github_pass:
        type: string
        required: true
      image_name:
        type: string
        required: true
      image_tag:
        type: string
        required: true

    
jobs:
  clair-scan:
    runs-on: ubuntu-latest
   
    steps:
      - name: use clair-scan
        id: clair-main-scan
        uses: bruce1237/github-workflow-center/.github/actions/clair-scan@main
        with:
          github_pass: ${{ inputs.github_pass }}
          image_name: ${{ inputs.image_name }}
          image_tag: ${{ inputs.image_tag }}
      
      - name: upload artifact if scan fails
        if: steps.clair-scan.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: clair-artifact
          path: |
            scan-report.json
            scan.log
            clair-whitelist.yml
          
      - name: last step
        shell: bash
        run: ls -lah
          
