name: test env deploy
on:
  workflow_call:
    inputs:
      env_name:
        type: string
        required: true
        description: 'the name of the env in repo settings'
  workflow_dispatch:
    inputs:
      env_name:
        type: string
        required: true
        description: 'the name of the env in repo settings'



jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo hello - ${{ inputs.env_name }}
      
   

  test-env-deploy:
    needs: do-something
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    steps:
      - name: test env
        run: echo "ENV pending" - ${{ inputs.env_name }}